export const FETCH_LATEST_NEWS = 'home/FETCH_LATEST_NEWS';
export const FETCH_LATEST_NEWS_SUCCESS = 'home/FETCH_LATEST_NEWS_SUCCESS';
export const FETCH_LATEST_NEWS_FAIL = 'home/FETCH_LATEST_NEWS_FAIL';

